version: '3'

services:
  # -------- NGINX Reverse Proxy -----------
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    label: com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/proxy/vhost.d:/etc/nginx/vhost.d
      - /mnt/data/www/data/arednteam.htpwd:/etc/nginx/arednteam.htpwd:ro
      - /mnt/data/nginx/certs:/etc/nginx/certs:ro
      - /mnt/data/nginx/html:/usr/share/nginx/html
  # -------- NGINX LetsEncrypt Companion  -----------
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/proxy/vhost.d:/etc/nginx/vhost.d
      - /mnt/data/nginx/certs:/etc/nginx/certs
      - /mnt/data/nginx/html:/usr/share/nginx/html
  # -------- APACHE2: downloads server -----------
  downloads:
    container_name: downloads
    environment:
      VIRTUAL_HOST: downloads.arednmesh.org
    image: httpd  # this will use httpd:latest
    expose:
      - 80
    restart: always
    volumes:
      - /mnt/data/www/downloads:/usr/local/apache2/htdocs:ro
      - ./config/downloads/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/downloads/httpd-autoindex.conf:/usr/local/apache2/conf/extra/httpd-autoindex.conf:ro
  # -------- APACHE2: usercontent server -----------
  usercontent:
    container_name: usercontent
    environment:
      VIRTUAL_HOST: usercontent.arednmesh.org
      LETSENCRYPT_HOST: usercontent.arednmesh.org
      LETSENCRYPT_EMAIL: dman776@gmail.com
    image: httpd  # this will use httpd:latest
    expose:
      - 80
    restart: always
    volumes:
      - /mnt/data/www/usercontent:/usr/local/apache2/htdocs:ro
      - ./config/usercontent/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/usercontent/httpd-autoindex.conf:/usr/local/apache2/conf/extra/httpd-autoindex.conf:ro
  # -------- MONGODB: data server -----------
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - /mnt/data/db:/data/db:rw
  # -------- SYSINFODB: map server -----------
  sysinfodb:
    container_name: sysinfodb
    depends_on:
      - mongodb
    environment:
      VIRTUAL_HOST: data.arednmesh.org
    image: arednmesh/sysinfodb  # this will use httpd:latest
    expose:
      - 8080
    restart: always
# -------- NETWORKS -----------
networks:
  default:
      external:
          name: proxy