version: '3'

services:
  proxy:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd  # this will use httpd:latest
    volumes:
        - ./mnt/data/www:/usr/local/apache2/htdocs:ro
  mapdata:
    image: python  # this will use httpd:latest
  mongodb:
    image: mongo
    #volumes:
    #    - ./mnt/data/db:/var/mongodb/db:rw