version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  downloads:
    container_name: downloads
    environment:
      VIRTUAL_HOST: downloads.arednmesh.org
    image: httpd  # this will use httpd:latest
    expose:
      - 80
    restart: always
    volumes:
      - /mnt/data/www/downloads/htdocs:/usr/local/apache2/htdocs:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      # - ./mnt/data/www/downloads/dir-index.cgi:/usr/local/apache2/cgi-bin/dir-index.cgi:ro
#  data:
#    container_name: data
#    environment:
#      VIRTUAL_HOST: data.arednmesh.org
#    image: httpd  # this will use httpd:latest
#    expose:
#      - 80
#    restart: always
#    volumes:
#      - /mnt/data/www/data:/usr/local/apache2/htdocs:ro
#
#  mapdata:
#   container_name: mapdata
#    image: python  # this will use httpd:latest

#  mongodb:
#    container_name: mongodb
#    image: mongo
#    volumes:
#      - ./mnt/data/db:/var/mongodb/db:rw

networks:
  default:
      external:
          name: proxy